LineLength:
  Description: 'Limit lines to 120 characters.'
  Max: 120

RedundantSelf:
  Enabled: false

SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

AlignParameters:
  EnforcedStyle: with_fixed_indentation

DotPosition:
  EnforcedStyle: leading

EmptyLinesAroundBody:
  Enabled: false

NumericLiterals:
  Enabled: false
