LineLength:
  Description: 'Limit lines to 120 characters.'
  Max: 120

StringLiterals:
  EnforcedStyle: single_quotes

RedundantSelf:
  Enabled: false

SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

AlignParameters:
  Enabled: false

DotPosition:
  EnforcedStyle: leading

EmptyLinesAroundBody:
  Enabled: false

NumericLiterals:
  Enabled: false

CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

CyclomaticComplexity:
  Enabled: false

MethodLength:
  Enabled: false

ClassLength:
  Enabled: false
