# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: sqlite3
  database: db/mnt/development.sqlite3
  pool: 5
  timeout: 5000

# See corresponding schema load in spec/support/in_memory_database
test:
  adapter: sqlite3
  database: ":memory:"
  verbosity: quiet

production:
  adapter: sqlite3
  database: db/mnt/production.sqlite3
  pool: 5
  timeout: 5000
