---
- name: Default
  default: true
- name: Wordpress
- name: Tomcat
- name: Rails
- name: NodeJS
- name: MySQL
- name: Magento
- name: LAMP
- name: Java
- name: HuBot
- name: Drupal
- name: Django
- name: Apache
- name: Ubuntu
- name: Alfresco
- name: Joomla
- name: Liferay
- name: Moodle
- name: odoo
- name: phpBB
- name: Redmine
- name: Subversion
- name: SugarCRM
- name: MAMP
- name: MediaWiki
- name: Trac
- name: WAMP
